-- STUDENT RESULTS TABLE
create table student_results (
    id bigint generated by default as identity primary key,

    student_name text not null,

    quiz_name text not null,

    score integer not null,

    total_items integer not null,

    created_at timestamptz default now()
);


-- ENABLE ROW LEVEL SECURITY
alter table student_results enable row level security;


-- Allow students' quiz results to be inserted
create policy "Allow students to submit results"
on student_results
for insert
to anon
with check (
    score >= 0
    and total_items > 0
    and score <= total_items
);


-- Allow authenticated admin users to view results
create policy "Allow admins to view results"
on student_results
for select
to authenticated
using (true);